server:
  port: 11001
  servlet:
    context-path: /product
spring:
  kafka:
    listener:
      ack-mode: manual
    consumer:
      auto-offset-reset: latest
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver