spring:
  datasource:
    username: postgres
    password: 900922
    url: jdbc:postgresql://10.1.28.182:5432/postgres
  redis:
    host: 10.1.28.182
    port: 6379
  kafka:
    bootstrap-servers: 10.1.28.182:9092