spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 900922
    url: jdbc:postgresql://10.1.12.100:5432/postgres
  redis:
    host: 10.1.12.100
    port: 6379